// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class SeedData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var userId1 = new Guid("a7f3a5c0-b8d9-4e2c-9f5b-8c7d6e5a4b3c");
            var userId2 = new Guid("b8e4b6d1-c9ea-5f3d-af6c-9d8e7f6b5c4d");

            migrationBuilder.InsertData(
                table: "users",
                schema: "public",
                columns: new[] { "id", "email", "first_name", "last_name", "password_hash" },
                values: new object[,]
                {
                    {
                        userId1,
                        "john.doe@example.com",
                        "John",
                        "Doe",
                        "48C5F6C7E8B9F1A2B3C4D5E6F7A8B9C0D1E2F3A-4B5C6D7E8F9A0B1C2D3E4F5A"
                    },
                    {
                        userId2,
                        "jane.smith@example.com",
                        "Jane",
                        "Smith",
                        "48C5F6C7E8B9F1A2B3C4D5E6F7A8B9C0D1E2F3A-4B5C6D7E8F9A0B1C2D3E4F5A"
                    }
                });

            migrationBuilder.InsertData(
                table: "todo_items",
                schema: "public",
                columns: new[] { "id", "user_id", "description", "due_date", "labels", "is_completed", "created_at", "completed_at", "priority" },
                values: new object[,]
                {
                    {
                        new Guid("c9f5a7d2-da0b-4e6e-9d7d-ae8f7c6d5e4f"),
                        userId1,
                        "Evi temizle",
                        new DateTime(2024, 12, 25, 0, 0, 0, DateTimeKind.Utc),
                        "[]",
                        false,
                        new DateTime(2024, 8, 12, 10, 0, 0, DateTimeKind.Utc),
                        null,
                        0
                    },
                    {
                        new Guid("d0e6b8e3-eb1c-5f6d-ae8e-bf0d9d8d7e6f"),
                        userId1,
                        "Projeyi tamamla",
                        new DateTime(2024, 8, 20, 17, 0, 0, DateTimeKind.Utc),
                        "[\"urgent\",\"work\"]",
                        false,
                        new DateTime(2024, 8, 12, 10, 0, 0, DateTimeKind.Utc),
                        null,
                        2
                    },
                    {
                        new Guid("e1f7c9f4-fc2d-6g7f-cf9f-cg1f0f9e8f7g"),
                        userId1,
                        "Market alışverişi",
                        new DateTime(2024, 8, 15, 14, 0, 0, DateTimeKind.Utc),
                        "[\"shopping\"]",
                        true,
                        new DateTime(2024, 8, 10, 9, 0, 0, DateTimeKind.Utc),
                        new DateTime(2024, 8, 12, 16, 0, 0, DateTimeKind.Utc),
                        1
                    },
                    {
                        new Guid("f2g8d0f5-gd3e-7h8g-dg0f-dh2g1g0f9g8h"),
                        userId2,
                        "Kodu incele",
                        new DateTime(2024, 8, 18, 15, 0, 0, DateTimeKind.Utc),
                        "[\"work\"]",
                        false,
                        new DateTime(2024, 8, 11, 11, 0, 0, DateTimeKind.Utc),
                        null,
                        2
                    },
                    {
                        new Guid("g3h9e1h6-he4f-8i9h-eh1g-ei3h2h1g0h9i"),
                        userId2,
                        "Egzersiz yap",
                        new DateTime(2024, 8, 13, 18, 0, 0, DateTimeKind.Utc),
                        "[\"health\"]",
                        false,
                        new DateTime(2024, 8, 12, 8, 0, 0, DateTimeKind.Utc),
                        null,
                        1
                    }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "todo_items",
                schema: "public",
                keyColumn: "id",
                keyValue: new Guid("c9f5a7d2-da0b-4e6e-9d7d-ae8f7c6d5e4f"));

            migrationBuilder.DeleteData(
                table: "todo_items",
                schema: "public",
                keyColumn: "id",
                keyValue: new Guid("d0e6b8e3-eb1c-5f6d-ae8e-bf0d9d8d7e6f"));

            migrationBuilder.DeleteData(
                table: "todo_items",
                schema: "public",
                keyColumn: "id",
                keyValue: new Guid("e1f7c9f4-fc2d-6g7f-cf9f-cg1f0f9e8f7g"));

            migrationBuilder.DeleteData(
                table: "todo_items",
                schema: "public",
                keyColumn: "id",
                keyValue: new Guid("f2g8d0f5-gd3e-7h8g-dg0f-dh2g1g0f9g8h"));

            migrationBuilder.DeleteData(
                table: "todo_items",
                schema: "public",
                keyColumn: "id",
                keyValue: new Guid("g3h9e1h6-he4f-8i9h-eh1g-ei3h2h1g0h9i"));

            migrationBuilder.DeleteData(
                table: "users",
                schema: "public",
                keyColumn: "id",
                keyValue: new Guid("a7f3a5c0-b8d9-4e2c-9f5b-8c7d6e5a4b3c"));

            migrationBuilder.DeleteData(
                table: "users",
                schema: "public",
                keyColumn: "id",
                keyValue: new Guid("b8e4b6d1-c9ea-5f3d-af6c-9d8e7f6b5c4d"));
        }
    }
}
